In [1]:
import urllib.request

urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fc11a705ee0>)

In [3]:
import numpy as np

In [4]:
climate_Data = np.genfromtxt('climate.txt', delimiter = ',', skip_header=1)

In [5]:
climate_Data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [7]:
climate_Data.shape

(10000, 3)

In [8]:
weights = np.array([0.3, 0.2, 0.5])

In [9]:
yields = climate_Data @ weights

In [10]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [11]:
yields.shape

(10000,)

In [12]:
yields = np.matmul(climate_Data, weights)

In [13]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [15]:
yields.shape

(10000,)

In [17]:
climate_Data = np.concatenate((climate_Data, yields.reshape(10000,1)), axis=1)

In [18]:
climate_Data

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [19]:
np.savetxt("climate_results.txt", climate_Data, fmt="%.2f", header='temperature, rainfall, humidity, yield_results', comments='')