In [4]:
import urllib.request

urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f9b7947f670>)

In [5]:
import numpy as np

In [6]:
climate_Data = np.genfromtxt('climate.txt', delimiter = ',', skip_header=1)

In [7]:
climate_Data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [8]:
climate_Data.shape

(10000, 3)

In [9]:
weights = np.array([0.3, 0.2, 0.5])

In [10]:
yields = climate_Data @ weights

In [11]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [12]:
yields.shape

(10000,)

In [13]:
yields = np.matmul(climate_Data, weights)

In [14]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [15]:
yields.shape

(10000,)

In [16]:
climate_Data = np.concatenate((climate_Data, yields.reshape(10000,1)), axis=1)

In [17]:
climate_Data

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [18]:
np.savetxt("climate_results.txt", climate_Data, fmt="%.2f", header='temperature, rainfall, humidity, yield_results', comments='')

In [19]:
arr1 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
arr2 = np.array([[1,2,3,4]])

In [20]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [21]:
#broadcasting

arr3 = np.sum((arr1, arr2))

/Users/mirakumar/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [22]:
arr3

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16],
       [14, 16, 18, 20]])

In [23]:
arr1 = np.array([[1,2,3,4],
                [1,2,3,4]])
arr2 = np.array([[1,2,3,4], [4,3,2,1]])

In [25]:
(arr1==arr2).sum() #true is 1 and false is 0

4

---

In [26]:
arr3 = np.array([[[11,12,13,14],
                 [14,15,19,20]],
                
                [[15,16,17,21],
                [43,56,71,67]],
                
                [[11,12,43,98],
                [78,99,34,58]]])

In [28]:
arr3[1,1,3]

67

In [29]:
arr3.shape

(3, 2, 4)

In [32]:
arr3[1:, :1, :2]

array([[[15, 16]],

       [[11, 12]]])

In [33]:
arr3[1:, :1, :2].shape

(2, 1, 2)

---

In [34]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.random.rand(5) #Rand is from 0-1

array([0.96845369, 0.14522386, 0.42596442, 0.025445  , 0.72055826])

In [42]:
np.random.randn(2,3)

array([[ 1.80463432, -0.48541251, -0.39520928],
       [ 1.59118759, -0.43214737, -0.11523037]])

In [44]:
np.full([2,3], 69)

array([[69, 69, 69],
       [69, 69, 69]])

In [45]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [46]:
np.arange(10,90,3).shape

(27,)

In [47]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [48]:
np.arange(10,90,3).reshape(1,27)

array([[10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55,
        58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88]])

In [49]:
np.arange(10,90,3).reshape(27,1)

array([[10],
       [13],
       [16],
       [19],
       [22],
       [25],
       [28],
       [31],
       [34],
       [37],
       [40],
       [43],
       [46],
       [49],
       [52],
       [55],
       [58],
       [61],
       [64],
       [67],
       [70],
       [73],
       [76],
       [79],
       [82],
       [85],
       [88]])

In [52]:
np.linspace(3,30,num=9)

array([ 3.   ,  6.375,  9.75 , 13.125, 16.5  , 19.875, 23.25 , 26.625,
       30.   ])

In [51]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

---